from abc import ABC, abstractmethod
from typing import Any

class GeneratorAbstractBaseClass(ABC):
    """
    Abstract interface for the Text Generator component.
    Enforces the contract for synthesizing retrieved context into a citation-aware answer.
    """

    @abstractmethod
    def generate(self, query: str, chunks: list[str], metadatas: list[dict[str, Any]]) -> str:
        """
        Constructs a prompt from the query and retrieved context, sends it to the LLM,
        and returns the generated answer.

        Args:
            query (str): The exact question asked by the user.
            chunks (list[str]): The raw text chunks retrieved from the vector store.
            metadatas (list[dict[str, Any]]): The corresponding metadata for each chunk.

        Returns:
            str: The final answer generated by the Large Language Model.
        """
        pass